### ISSUE TITLE
taking sentences only from one file.

### ISSUE THREAD

**Issue by shubhrai2811** [GDSC-IIIT-Kalyani/Typing-Speed-Test#4]
Takes sentences only from a single file. need to take random sentences from multiple different files.

**Comment by Ansh-Sarkar** [comment]
Hi ! Would love to work on this issue. Kindly do assign it to me.

Also, had a small doubt, What we are trying to achieve is, rather than taking the sentences only from the ```sentences.txt``` file, we would have a pool of text files. We first need to randomly select one of the text files and then select one random sentence from that text file. That's the case right ? So in the end, the output is just a single sentence randomly chosen from the pool of possible sentences.

Do correct me if I am wrong. Would love to contribute. Thanks !

**Comment by Adinapunyo-Banerjee** [comment]
Why not use an API and get completely random sentences each round?

**Comment by MashyBasker** [comment]
Hello @shubhrai2811 I'd like to take up this issue if it's alright
